# This file is part of Mconf-Web, a web application that provides access
# to the Mconf webconferencing system. Copyright (C) 2010-2012 Mconf
#
# This file is licensed under the Affero General Public License version
# 3 or later. See the LICENSE file.

module DatesHelper

  # Method to insert a title containing the full date in a date generated by "time_ago_in_words".
  def time_to_be_shown(title=nil, text=nil, options={})
    options[:class] = options.has_key?(:class) ? "thread-updated-at " + options[:class] : "thread-updated-at"
    options[:title] = title unless title.nil? or title.blank?
    content_tag :span, text, options
  end

end
