#!/usr/bin/env ruby

LINUX_PACKAGES = {
  :common => %w( ruby-dev rdoc irb libopenssl-ruby wget make curl aspell-es aspell-en libxml2-dev libxslt-dev libmagickcore-dev libmagickwand-dev ),
  :production => %w( awstats logrotate nfs-common ),
  :development => %w( ),
  :mysql  => %w( libmysqlclient15-dev mysql-server ),
  :sqlite => %w( libsqlite3-dev )
}
RUBY_GEMS_VERSION = "1.3.6"
RUBY_GEMS_PACKAGE = "rubygems-#{ RUBY_GEMS_VERSION }.tgz"
RUBY_GEMS_DOWNLOAD = "http://rubyforge.org/frs/download.php/60718/#{ RUBY_GEMS_PACKAGE }"

GEMS = {
  #TODO: get rails version from config/environment.rb
  :common     => [ "rails -v 2.3.4",
                   "rmagick",
                   "rake",
                   "vpim",
                   "ruby-debug",
                   "ruby-openid",
                   "atom-tools",
                   "mislav-will_paginate -s http://gems.github.com/",
                   "rcov",
                   "chronic",
                   "hpricot",
                   "feed-normalizer",
                   "rspec-rails -v 1.3.2",
                   "hoe",
                   "httparty",
		   "pdf-writer",
                   "ci_reporter",
                   "nokogiri -v 1.4.1",
                   "prism",
                   "rubyzip" ],
  :production  => [ ],
  :development => [ "capistrano",
                    "mongrel",
                    "populator",
                    "faker",
                    "thoughtbot-factory_girl -s http://gems.github.com/"
                     ],
  :mysql => [ "mysql" ],
  :sqlite => [ "sqlite3-ruby" ]
}

DATABASES = %w( MySQL SQLite )

def install_linux_packages(set)
  return unless `uname`.chomp == "Linux" && `which aptitude` != ""

  puts "* Install #{ set } Linux packages"
  if LINUX_PACKAGES[set].any?
    system "sudo aptitude install #{ LINUX_PACKAGES[set].join(" ") }"
  end
end

def install_gems(set)
  puts "Installing #{ set } gems.."
  GEMS[set].each do |gem|
    puts "Installing gem: #{ gem }"
    system "sudo gem install #{ gem } --no-ri --no-rdoc"
  end
end

def install_gem_subsystem
  if `which gem`.chomp == ""
    gem_bin = `which gem1.8`.chomp
    if gem_bin == ""
      puts "Installing Ruby Gems"
      system "cd /tmp && wget #{ RUBY_GEMS_DOWNLOAD }"
      system "cd /tmp && tar zxf #{ RUBY_GEMS_PACKAGE }"
      system "cd /tmp/rubygems-#{ RUBY_GEMS_VERSION } && sudo /usr/bin/ruby setup.rb"
    end
    system "sudo ln -s /usr/bin/gem1.8 /usr/bin/gem"
  end
end

def install_database
  print "* Checking config/database.yml: "

  db_file = File.dirname(__FILE__) + "/../config/database.yml"

  if File.exist?(db_file)
    puts "file exists. Assuming configurated database."
    return
  end

  db_type = ask_for_db_type
  install_linux_packages(db_type)
  install_gems(db_type)

  `cp #{ db_file }.#{ db_type }.example #{ db_file }` 

  if db_type == :mysql
    puts
    puts "***************************************************************"
    puts
    puts "MySQL support installed."
    puts "Please, configure your MySQL database and run the script again."
    exit(-1)
  end
end

def ask_for_db_type
  puts
  puts "Which database do you want to install?"
  DATABASES.each_with_index do |db, index|
    puts "#{ index + 1 }. #{ db }"
  end

  until ( number = STDIN.gets.chomp ) =~ /[12]/
    puts "Please, choose 1 or 2"
  end 

  DATABASES[ number.to_i - 1].downcase.to_sym
end

def setup_environment(env)
  install_linux_packages(:common)
  install_linux_packages(env)
  install_gem_subsystem
  install_gems(:common)
  install_gems(env)
  install_database
  system "rake setup:#{ env }"
end

def print_banner(env)
  puts
  puts "------------------------------"
  puts "Setting #{ env } environment"
  puts "------------------------------"
  puts
end

if ARGV[0] =~ /production/
  print_banner("PRODUCTION")
  setup_environment(:production)
else
  print_banner("DEVELOPMENT")
  setup_environment(:development)
end
